import assert from 'node:assert/strict';
import { createBackend, serializeEvent, decodeRow } from '../lib/backend.js';

const id = 'fa64db1f-9631-4a42-9168-5d1a28f96f1f';
const calls = [];
let reply = { id, tag: 'Batty' };
const api = createBackend({ async rpc(name, args) { calls.push({ name, args }); return { data: reply }; } });
const rules = { matchFormat: { firstTo: 2 } };
const event = serializeEvent({ name: 'Weekly', ownerId: 'attacker', inviteCode: 'secret',
  orgName: 'Batty', overrides: rules, stations: [{ label: 'One', platform: 'ps5', id: 'unsafe' }] });
assert.deepEqual(event, { name: 'Weekly', org_name: 'Batty', overrides: rules, stations: [{ label: 'One', platform: 'ps5' }] });
event.overrides.matchFormat.firstTo = 3;
assert.equal(rules.matchFormat.firstTo, 2);
assert.throws(() => serializeEvent({ demo: true }), /cannot be published/);
assert.throws(() => serializeEvent({ local: true }), /cannot be published/);
assert.throws(() => serializeEvent({ entryFee: 10 }), /must be free/);
assert.deepEqual(decodeRow({ player_id: id, overrides: rules }), { playerId: id, overrides: rules });
assert.equal((await api.identity()).id, id);
assert.deepEqual(calls.pop(), { name: 'bkt_identity', args: { p_tag: null } });
await assert.rejects(api.readEvent('evt_local'), /UUID/);
await api.joinEvent(id, { contact: 'private@example.com', shareContact: false, seed: 1, paid: true });
assert.deepEqual(calls.pop(), { name: 'bkt_join_event', args: { p_event_id: id, p_contact: null, p_share_contact: false } });
await api.joinEvent(id, { contact: 'ok@example.com', shareContact: true });
assert.equal(calls.pop().args.p_contact, 'ok@example.com');
reply = { event: { id, org_id: id }, org: { id }, stations: [], invite_code: 'CODE' };
assert.equal((await api.createEvent(id, { name: 'Weekly' })).inviteCode, 'CODE');
assert.equal(calls.pop().args.p_event_id, id);
reply = { error: 'rate_limited' };
await assert.rejects(api.redeemCode('foo'), /Too many/);
reply = null;
await assert.rejects(api.identity(), /acknowledgement/);
const failing = createBackend({ async rpc() { return { error: { message: 'Permission denied' } }; } });
await assert.rejects(failing.identity(), /Permission denied/);
let resolve;
const pending = createBackend({ rpc() { return new Promise(done => { resolve = done; }); } });
const oldAccount = pending.identity();
pending.invalidate();
resolve({ data: { id, tag: 'Previous account' } });
await assert.rejects(oldAccount, /Account changed/);
console.log('PASS backend client: explicit payloads, identity, consent, errors, account race, and local-data boundary');
